### ISSUE TITLE
Hi, and checking if PKGBUILD is outdated.

### ISSUE THREAD

**Issue by phcerdan** [CharlesGueunet/aur-paraview-ttk#1]
Hi @CharlesGueunet, I was about to give it a try to ttk, it looks super good, and I am really interested in digital topology. I have contributed skeletonization algorithms in the past to [DGtal](https://github.com/DGtal-team/DGtal).

I am on Archlinux as well, and I wonder if this PKGBUILD of yours is still a good way to install ttk or got outdated. Or would you recommend following the [installation steps of the documentation](https://topology-tool-kit.github.io/installation.html) (even though they are ubuntu).

Thanks!

**Comment by vollia** [comment]
Hello @phcerdan ,

I am glad you are interested in TTK,
unfortunately, this AUR is out of date for now. I will update it when I have some spare time... but not for now, sorry. I would recommend to use the official documentation you mention instead.
The PKGBUILD can still be useful for the list of dependency on Arch linux.

Anyway if you have any trouble during install, feel free use the mailing list:
[ttk-users@googlegroups.com](ttk-users@googlegroups.com)

Charles

**Comment by phcerdan** [comment]
Thanks @CharlesGueunet, I'll do.
